#lang planet neil/sicp

(define (make-account money password) 
  (define (withdraw pwd amount)
    (if (eq? pwd password)
        (if (>= money amount)
            (begin (set! money (- money amount))
                   money)
            "Insufficient Account")
        "Wrong Password, Sir --Withdraw"))
  (define (deposit pwd amount)
    (if (eq? pwd password)
        (begin (set! money (+ money amount))
               money)
        "Wrong Password, Sir --Deposit"))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "No Such Command:" m))))
  dispatch)

(define acc (make-account 100 'pku))
((acc 'withdraw) 'pku 20)
((acc 'withdraw) 'pku 110)
((acc 'withdraw) 'pku1 20)
((acc 'deposit) 'pku 30)
((acc 'deposit) 'pku1 20)
((acc 'hello) 'pku1 20)